apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap30-ride-demand-mlops
  namespace: tap30
  labels:
    app: tap30-ride-demand-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tap30-ride-demand-mlops
  template:
    metadata:
      labels:
        app: tap30-ride-demand-mlops
    spec:
      containers:
        - name: tap30-ride-demand-mlops
          image: amirali3100/tap30-ride-demand-mlops:0.1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
