data_ingestion:
  bucket_name: "tap30-model"
  object_name: "data.txt"
  storage_path: "s3.ir-thr-at1.arvanstorage.ir"
  train_ratio: 0.9
  artifact_dir: "artifacts"

data_processing:
  shift: 18

model_training:
  n_estimators: 500
  max_samples: 0.7
  n_jobs: -1
